logbook:
  write:
    max-body-size: 10

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql